#include "stdafx.h"

#include "Core.h"

// Modules Include
#include "Modules/Network/ModuleNetworking.cpp"
#include "Modules/Network/ModuleNetworkingClient.cpp"
#include "Modules/Network/ModuleNetworkingServer.cpp"
#include "Modules/Scene/ModuleGameObject.cpp"
#include "Modules/Foundation/ModulePlatform.cpp"
#include "Modules/Rendering/ModuleRender.cpp"
#include "Modules/Foundation/ModuleResources.cpp"
#include "Modules/Scene/ModuleScreen.cpp"
#include "Modules/Foundation/ModuleTaskManager.cpp"
#include "Modules/Rendering/ModuleTextures.cpp"
#include "Modules/Scene/ModuleUI.cpp"
#include "Core.cpp"
#include "Screens/ScreenLoading.cpp"
#include "Screens/ScreenBackground.cpp"
#include "Screens/ScreenOverlay.cpp"
#include "Screens/ScreenMainMenu.cpp"
#include "Screens/ScreenGame.cpp"
#include "Core/Application.cpp"
#include "Core/main.cpp"